### ISSUE TITLE
Update node-nats-streaming

### ISSUE THREAD

**Issue by marcoreni** [hemerajs/hemera-nats-streaming#5]
Hello,

I just realized that node-nats-streaming is fixed to 0.0.28 ( Semver fixes exact version for `^0.0.x` , ref: https://nodesource.com/blog/semver-tilde-and-caret/#caretmajorzero ). Can we safely update to 0.0.41 (latest released version)?. This would help solve https://github.com/nats-io/node-nats-streaming/issues/73 among others.

**Comment by StarpTech** [comment]
Sure, add it to the open PR.
