### ISSUE TITLE
Is this plugin production ready - how can it work with multiple services?

### ISSUE THREAD

**Issue by rafsawicki** [hemerajs/hemera-nats-streaming#6]
Sorry if this post comes out rude in any way, but we tried to use this plugin in our upcoming project (given that it's mentioned in the Hemera documentation) and it turned into hours of trying to make sense of the things that we were seeing in logs. When I finally went looking into the source code I was surprised to say the least, and still have no idea how it's supposed to be working with more than one service. I'll give an example to illustrate what I mean.

From what I gather, this plugin more or less works in the following way (please correct me if I'm wrong at any point):
For publishing:
- On connect, add a Hemera handler on `natss` topic with `publish` command
- In this handler, emit a NATS streaming event with a subject passed as a parameter

For subscriptions:
- Create a NATS streaming subscription when `hemera.natss.add` method is used
- When an event is received from NATS streaming, execute Hemera.act with `natss.event-subject` topic from a subscription handler
- Events can be listened by adding a Hemera handler on `natss.subject` topic

Now, let's imagine that we have 3 independent services, all using Hemera with Hemera-nats-streaming plugin. Let's call them A, B and C.  An event with a subject `user-created` is published by A, while B and C wish to subscribe to it. 

1. On B and C we create a NATS steaming subscription via
```
hemera.natss.add({
  subject: 'user-created'
})
```
and then add a handler via Hemera
```
hemera.add({ topic: 'natss.user-created' }, async () => { })
```
2. On A, we publish the message with
```
hemera.act({
  topic: 'natss',
  cmd: 'publish',
  subject: 'user-created',
  data: { }
})
```

At this point strange things start to happen:

3. Random service (A, B or C) handles the Hemera call and emits the actual event to NATS streaming

I don't know why events are first passed through NATS with Hemera before being published in NATS streaming (is this a Hemera plugin limitation?), but since all services have handler on the same `natss` topic, it gets routed to a randomly selected one, instead of the one that tries to emit an event in a first place.

At this point it still works correctly, even though the network traffic is doubled and it's very confusing to debug (for example, event handler error logs end up in random services).

4. B and C both receive the event inside the NATS streaming subscription in the plugin

Looking good at this point, every service received the event just as intended

5. From a plugin, B and C both make a Hemera request that contains the event with `natss.user-created` topic

At this point all hell breaks loose. We have two services listening on a topic `natss.user-created`. This means that any of the following scenarios can happen, at random:
- A receives the event twice, B never gets it
- B receives the event twice, A never gets it
- Both A and B get the event once

You can imagine how difficult it was to debug, given that it works correctly (though not efficiently) with a single listener for a given event, but breaks as soon as you add a second one and only get worse with more.

It seems less like a bug and more like a flaw in a way that a plugin is designed, so I don't know what the solution should be here. Things that comes to my mind are:
- if we have completely misused this plugin somehow, please make it clear in the documentation on how it should be used with more than one service
- if it's not meant to be used in production, please make it explicit in the Hemera documentation

If it's possible to intercept Hemera in a way that would allow passing events in memory (both when publishing and subscribing) I think it would resolve most of the issues, but I don't know if Hemera allows it in a first place.

**Comment by rafsawicki** [comment]
I've created a repository demonstrating the issue [here](https://github.com/rafsawicki/hemera-nats-streaming-test/). Please take a look at it if my explanation is not clear enough.

**Comment by StarpTech** [comment]
Hi @rafsawicki 
this plugin is used to ensure that a message was acknowledged by the hemera client. It act as a reply mechanism for hemera. This plugin will distribute the message via `publish` to all interested hemera clients in random order (default behaviour of nats-streaming). If you want to change it, you have to define a [`queue-group`](https://github.com/nats-io/node-nats-streaming#queue-groups) then only one client will receive the request.

```js
  hemera.natss.add({
    subject: 'user-created',
    queue: 'user.created', // (optional) nats-streaming queue group
  });
```

> if we have completely misused this plugin somehow, please make it clear in the documentation on how it should be used with more than one service

If you are not fully in the topic the plugin can a bit hard to understand.

> if it's not meant to be used in production, please make it explicit in the Hemera documentation

It is meant to be used in production!

I hope this could help you.

**Comment by rafsawicki** [comment]
Hello @StarpTech 
We want all of the clients to receive the message, that's why we're not using queue groups. Also, random ordering is also not an issue (as expected with events after all).

It's the distribution part that you mentioned that doesn't work correctly and is causing the most issues. When NATS streaming subscription listener [receives the event](https://github.com/hemerajs/hemera-nats-streaming/blob/master/index.js#L134) it tries to pass is back to a local handler by using [hemera.act](https://github.com/hemerajs/hemera-nats-streaming/blob/master/index.js#L151). This part won't work with more than one service listening for the same event, because of the way that routing works in NATS when there is more than one listener on the same topic. Sometimes NATS sends both messages to one service and none to the other one (point 5 in my original message).

If possible, please take a look at my repository which shows this issue. I start a publisher there and 3 subscribers listening to the same event. If it would all work fine, every subscriber should get the event exactly once (given no network issues that could cause ACK errors). But that's not what happens as you can see from the logs.

![image](https://user-images.githubusercontent.com/2313294/49143959-7b5a5c80-f2fc-11e8-8f1f-b61d8ef33466.png)

**Comment by StarpTech** [comment]
Hi @rafsawicki I will check your setup at the weekend ATM no time.

**Comment by StarpTech** [comment]
@rafsawicki I checked your setup shortly I found following issues:

* You must not create a `nats-streaming` subscription for a hemera subscriber. The `durable`  subscription is created for the service which want to ensure that the message was acknowledged in that case it's the `publisher.js`. In case of an error (when the message was not received by one of the subscribers) the message is replayed.

* By default any request by hemera has `request/reply` semantic that means `queue-groups` are enabled. In your case you want to send it to all services. That's why you need to set the transport option `pubsub$: true` on the hemere subscription in the `subscriber.js` file.

If you respect both points it will work.

**publisher.js**
```js
const Hemera = require("nats-hemera");
const nats = require("nats").connect();
const hemeraNatsStreaming = require("hemera-nats-streaming");

const hemera = new Hemera(nats, {
  logLevel: "warn"
});

hemera.use(hemeraNatsStreaming, {
  clusterId: "test-cluster",
  clientId: "publisher",
  options: {} // NATS/STAN options
});

let eventId = 1;
hemera.ready(() => {
  hemera.natss.add({
    subject: "user-created",
    options: {}, // (optional) nats-streaming transport options
    pattern: {} // (optional) the pattern which arrive hemera
  });

  setInterval(async () => {
    console.log("\npublisher: Publishing an event with id", eventId);
    await hemera.act({
      topic: "natss",
      cmd: "publish",
      subject: "user-created",
      data: { eventId: eventId }
    });
    eventId += 1;
  }, 3000);
});
```
**subscriber.js**
```js
const Hemera = require('nats-hemera');
const nats = require('nats').connect();
const hemeraNatsStreaming = require('hemera-nats-streaming');
const chalk = require('chalk');

const subscriberName = process.argv[2];
if (subscriberName == null) {
  throw new Error('Missing subscriber name');
}

const hemera = new Hemera(nats, {
  logLevel: 'warn',
});

hemera.use(hemeraNatsStreaming, {
  clusterId: 'test-cluster',
  clientId: subscriberName,
  options: {}, // NATS/STAN options
});

const receivedEventIds = new Set();

hemera.ready(() => {
  hemera.add({ topic: 'natss.user-created', pubsub$: true }, (msg) => {
    const eventId = msg.data.message.eventId;

    if (receivedEventIds.has(eventId)) {
      console.log(chalk.bold.red(`Received duplicate event with id ${eventId}`));
    } else if (eventId > 1 && !receivedEventIds.has(eventId - 1)) {
      console.log(chalk.yellow(`Received an event with id ${eventId} but previous is missing`));
    } else {
      console.log(`Received an event with id ${eventId}`);
    }

    receivedEventIds.add(eventId);

    return Promise.resolve();
  });
});
```

**Comment by StarpTech** [comment]
@rafsawicki But have in mind when you want to have multiple `publishers` you need a queue group otherwise your subscribers will receive duplicates.

e.g

```js
  hemera.natss.add({
    subject: "user-created",
    queue: 'user.created',
    options: {}, // (optional) nats-streaming transport options
    pattern: {} // (optional) the pattern which arrive hemera
  });
```

**Comment by rafsawicki** [comment]
Thank you for explaining that @StarpTech . It's not really obvious that NATS streaming subscription must be created on the publisher and not on the subscriber, as it's the reverse of what has to be done with node-nats-streaming. However, with that said, the following question come to my mind - how do you handle scaling of multiple subscribers?

Let's say that we have 2 services - notification service and payment service, and they subscribe to the "user-created" event. We now want to scale up to have 2 instances of each of them. When using just node-nats-streaming it's easy - make all instances of a notification service part of a "notification-service" group and all instances of the payment service part of the "payment-service" group. This ensures that only one of the instances of each will process the event. How one should handle this scenario when using this library?

**Comment by StarpTech** [comment]
@rafsawicki I don't know if I understand your question correctly.

1. You have two different services which can be scaled infinitely
2. The events should be distributed in random order and at least one event should arrive at each type of service.

You can have only one queue-group per topic. You have to use a unique `queue` on the susbcriber side e.g

subscriber.js
```js
const Hemera = require('nats-hemera');
const nats = require('nats').connect();
const hemeraNatsStreaming = require('hemera-nats-streaming');

const subscriberName = process.argv[2];
if (subscriberName == null) {
  throw new Error('Missing subscriber name');
}
const queueName = process.argv[3];
if (queueName == null) {
  throw new Error('Missing queue name');
}

const hemera = new Hemera(nats, {
  logLevel: 'warn',
});

hemera.use(hemeraNatsStreaming, {
  clusterId: 'test-cluster',
  clientId: subscriberName,
  options: {}, // NATS/STAN options
});

hemera.ready(() => {
  hemera.add({ topic: 'natss.user-created', queue$: queueName }, (msg) => {
    const eventId = msg.data.message.eventId;

    console.log(`Received an event with id ${eventId}`);

    return Promise.resolve();
  });
});
```

publisher.js
```js
const Hemera = require("nats-hemera");
const nats = require("nats").connect();
const hemeraNatsStreaming = require("hemera-nats-streaming");

const publisherName = process.argv[2];
if (publisherName == null) {
  throw new Error('Missing subscriber name');
}

const hemera = new Hemera(nats, {
  logLevel: "warn"
});

hemera.use(hemeraNatsStreaming, {
  clusterId: "test-cluster",
  clientId: publisherName,
  options: {} // NATS/STAN options
});

let eventId = parseInt(process.argv[3]);
hemera.ready(() => {
  hemera.natss.add({
    subject: "user-created",
    options: {}, // (optional) nats-streaming transport options
    pattern: {} // (optional) the pattern which arrive hemera
  });

  setInterval(async () => {
    console.log("\npublisher: Publishing an event with id", eventId);
    await hemera.act({
      topic: "natss",
      cmd: "publish",
      subject: "user-created",
      data: { eventId: eventId }
    });
    eventId += 1;
  }, 3000);
});
```

in that way the published events are distributed two both groups

**Comment by StarpTech** [comment]
If would be great if you could create a PR with an improved documentation and examples 😄

**Comment by rafsawicki** [comment]
I had no idea that Hemera allowed to explicitly set a NATS queue group! I scrolled through the documentation (also tried googling "queue$ site:https://hemerajs.github.io/hemera/docs/") but I couldn't find more information about it.

If that's the case however, now it's clear on how the scenario that I've mentioned could be implemented.

In current project, we'll most likely stick to using node-nats-streaming directly to avoid doubling the traffic that goes through the NATS server (it's a IoT project, so we expect quite a few events coming by).  For future projects however, now when it's clear on how the scaling should be handled, we'll most likely use hemera-nats-streaming again, as we'd like to use the same Hemera API for handling events and commands.

Thank you very much @StarpTech for taking your time to respond to my questions.

**Comment by StarpTech** [comment]
@rafsawicki you are welcome!

**Comment by StarpTech** [comment]
> I had no idea that Hemera allowed to explicitly set a NATS queue group! I scrolled through the documentation (also tried googling "queue$ site:hemerajs.github.io/hemera/docs") but I couldn't find more information about it.

I just have seen it there are no hints in the documentation. I will improve it.

> In current project, we'll most likely stick to using node-nats-streaming directly to avoid doubling the traffic that goes through the NATS server (it's a IoT project, so we expect quite a few events coming by)

The idea behind this plugin was to use it optionally. Most of the requests don't need a delivery guarantee. In that case, you can increase the throughput and reduce the complexity.

**Comment by rafsawicki** [comment]
> The idea behind this plugin was to use it optionally. Most of the requests don't need a delivery guarantee. In that case, you can increase the throughput and reduce the complexity.

I thought that using nats streaming directly provided a delivery guarantee already (at least when publishing a message)? What are the additional guarantees provided by this library?
```javascript
  stan.publish('foo', 'message', function(err, guid){
    if(err) {
      console.log('publish failed: ' + err);
    } else {
      console.log('published message with guid: ' + guid);
    }
  });
```

**Comment by rafsawicki** [comment]
I think I figured it out. Since the NATS streaming subscription exists on the publisher now, we get an error if there are no subscribers to receive the event.

With regular node-nats-streaming we only know if event has reached the NATS streaming server.

**Comment by StarpTech** [comment]
> I thought that using nats streaming directly provided a delivery guarantee already (at least when publishing a message)? What are the additional guarantees provided by this library?

Yes, you are safe. I just wanted to mention that guaranteed delivery isn't required for all cases especially in IoT which could produce thousands of calls per day. That's why it is very useful when you can use Hemera and nats-streaming in one solution.

* Hemera -> sensor report
* Nats-streaming -> setting adjustment (temperature change)

> I think I figured it out. Since the NATS streaming subscription exists on the publisher now, we get an error if there are no subscribers to receive the event.

With regular node-nats-streaming we only know if event has reached the NATS streaming server.

That's indeed a good point. In `nats-streaming` there are no `request/reply` semantic. If you publish something it doesn't mean that the requestor has received it but it will guarantee that the messages are persistent and replayed in the way you defined it.
