### ISSUE TITLE
plugin did not start in time

### ISSUE THREAD

**Issue by agc11** [hemerajs/hemera-nats-streaming#7]
Error when use plugins in hemera, ERR_AVVIO_PLUGIN_TIMEOUT: plugin did not start in time.

**Comment by StarpTech** [comment]
Please rephrase and create a proper issue. I don't understand your issue.

**Comment by StarpTech** [comment]
According to your issue, you run into a plugin timeout because `nats-streaming` could not establish a connection to the server within 10sec. Did you start the `nats-streaming` server?

**Comment by agc11** [comment]
ok sorry, my fault
